service: dynamo-triggers # NOTE: update this with your service name

custom: ${file(./serverless.env.yml)}

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    $ref: ./resources/lambda-policy.json

plugins:
  - serverless-plugin-write-env-vars

functions:
  print:
    handler: print.processData

resources:  
  Resources:
    Event: 
      $ref: ./resources/event.json
    Table: 
      $ref: ./resources/table.json