service: dynamo-triggers # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1
  iamRoleStatements:
   - Effect: Allow
     Action:
      - dynamodb:GetRecords
      - dynamodb:GetShardIterator
      - dynamodb:DescribeStream
      - dynamodb:ListStreams
     Resource:
       Fn::GetAtt: 
        - Table
        - StreamArn

functions:
  print:
    handler: print.processData

resources:  
  Resources:
    Table:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:service}-spike
        AttributeDefinitions:
        - AttributeName: "Identifier"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "Identifier"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    Event:
      Type: AWS::Lambda::EventSourceMapping
      Properties:
        BatchSize: 10
        EventSourceArn:
          Fn::GetAtt:
            - Table
            - StreamArn      
        FunctionName:
          Fn::GetAtt:
            - PrintLambdaFunction
            - Arn
        StartingPosition: TRIM_HORIZON